Feature/identificar equipos
AdrianNYV/PRIA pull request #12
Opened 2023-01-19 21:36 UTC by DavidVidaMi

Añadidos métodos para devolver de que equipo e clase son.

2023-01-19 21:38 UTC, DavidCorbelle requested changes

2023-01-19 21:38 UTC, DavidCorbelle commented on main.cs
> +        public void setTeam(string team){
Podrías poner la variable como protected y en vez de crear este método asignarlo en el constructor como base.team=????  ya que no se va a utilizar el método en ningún otro caso

2023-01-23 16:57 UTC, noevilamunoz approved these changes

2023-01-23 16:59 UTC, DavidCorbelle approved these changes

2023-01-23 16:59 UTC, AdrianNYV approved these changes

2023-01-23 17:01 UTC, merged