Freature/clases
AdrianNYV/PRIA pull request #4
Opened 2023-01-17 19:44 UTC by DavidCorbelle

Ahora si compila

2023-01-17 19:46 UTC, DavidVidaMi approved these changes
Ahora sí compila, confirmamos

2023-01-17 19:51 UTC, AdrianNYV approved these changes
Confirmo Compila

2023-01-18 11:39 UTC, noevilamunoz requested changes
Revisade os dous comentarios que vos deixo no código. Cando os arregledes debería estar para mergear.

2023-01-18 11:39 UTC, noevilamunoz commented on main.cs
> +            this.atack=atack;
**Typo** Sigue o _typo_ revisade a ortografía

2023-01-18 11:39 UTC, noevilamunoz commented on main.cs
> +        Console.WriteLine("ZAWARDO");
**Dúbida:** ¿Isto é necesario? Se non aporta ao programa mellor eliminalo

2023-01-18 17:29 UTC, noevilamunoz approved these changes

2023-01-18 17:30 UTC, merged